name: Publish Package

on:
  release:
    types: [created]
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: Git configuration
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clean install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run lint
        run: npm run lint

      - name: Create .npmrc
        run: |
          echo "Creating .npmrc file..."
          cat > .npmrc << EOF
          registry=https://registry.npmjs.org/
          //registry.npmjs.org/:_authToken=${NPM_TOKEN_WATCHDOCK}
          save-exact=true
          package-lock=true
          access=public
          engine-strict=true
          node-version=20.17.0
          EOF
          echo "Checking if .npmrc was created:"
          ls -la .npmrc
          echo "Content of .npmrc (with token hidden):"
          cat .npmrc | sed 's/_authToken=.*/_authToken=***/'
        env:
          NPM_TOKEN_WATCHDOCK: ${{ secrets.NPM_TOKEN_WATCHDOCK }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Debug Token
        run: |
          echo "Token exists: ${{ secrets.NPM_TOKEN_WATCHDOCK != '' }}"
          echo "First few characters of token: ${NPM_TOKEN_WATCHDOCK:0:4}***"
        env:
          NPM_TOKEN_WATCHDOCK: ${{ secrets.NPM_TOKEN_WATCHDOCK }}

      - name: Create .npmrc
        run: |
          cat > .npmrc << EOF
          registry=https://registry.npmjs.org/
          //registry.npmjs.org/:_authToken=${NPM_TOKEN_WATCHDOCK}
          save-exact=true
          package-lock=true
          access=public
          engine-strict=true
          node-version=20.17.0
          EOF
          chmod 0600 .npmrc
        env:
          NPM_TOKEN_WATCHDOCK: ${{ secrets.NPM_TOKEN_WATCHDOCK }}

      - name: Git configuration
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ github.repository }}.git
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Install dependencies
        run: |
          npm ci
        env:
          NPM_TOKEN_WATCHDOCK: ${{ secrets.NPM_TOKEN_WATCHDOCK }}

      - name: Build
        run: npm run build

      - name: Version and Publish
        run: |
          echo "Checking NPM token..."
          if [ -z "$NPM_TOKEN_WATCHDOCK" ]; then
            echo "NPM_TOKEN_WATCHDOCK is not set"
            exit 1
          fi

          echo "Pulling latest changes..."
          git pull origin main

          echo "Creating new version..."
          npm version patch -m "🚀 Release %s [skip ci]"

          echo "Pushing changes..."
          git push origin HEAD:main --follow-tags

          echo "Publishing to NPM..."
          npm publish
        env:
          NPM_TOKEN_WATCHDOCK: ${{ secrets.NPM_TOKEN_WATCHDOCK }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Print completion message
        if: success()
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "✅ Successfully published version $VERSION to npm"
          echo "🔗 Package URL: https://www.npmjs.com/package/watchdock/v/$VERSION"
